# Generated by Django 5.1.3 on 2024-12-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('wishlists', '0002_alter_wishlistitem_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'product')},
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['wishlist', 'product'], name='wishlists_w_wishlis_37a3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['created_at'], name='wishlists_w_created_562265_idx'),
        ),
    ]
