auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester:
  wal:
    enabled: true
    dir: /loki/wal
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
      heartbeat_timeout: 1m

memberlist:
  join_members:
    - "loki"

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
    cache_ttl: 24h

  filesystem:
    directory: /loki/chunks

limits_config:
  max_streams_per_user: 10000
  max_entries_limit_per_query: 5000
  allow_structured_metadata: false

compactor:
  retention_enabled: true
  retention_delete_delay: 2h
  compaction_interval: 10m
  delete_request_store: filesystem
  working_directory: /loki/compactor

query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true

frontend:
  log_queries_longer_than: 5s
  compress_responses: true
