global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "django"
    static_configs:
      - targets: ["django-1:8000", "django-2:8001", "django-3:8002"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
